/* eslint-disable max-len */
import { DoughSize, Size } from '../types/pizza';
import { Section } from '../types/section';

export const mockDataAvaliblePizza: Array<Section> = [
  {
    products: [
      {
        id: '1',
        image: 'https://kingpizza.kh.ua/resources/products/20211123202045_366bb8053.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 220,
        toppings: '(double portion of mushrooms), mushrooms, mozzarella, pepperoni, alfredo sauce',
        name: 'Pizza Manhattan',
      },
      {
        id: '2',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 220,
        toppings: 'mozzarela, peperoni, tomatos, barbeque sause',
        name: 'Pizza Peperoni with tomato',
      },
      {
        id: '3',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 220,
        toppings: 'ham, mushrooms, mozzarella, Domino\'s Sauce',
        name: 'Pizza ham and mushroom',
      },
      {
        id: '4',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 220,
        toppings: 'corn, onion, mushrooms, bavarian sausages, mozzarella, barbecue sauce',
        name: 'Pizza Texas',
      },
    ],
    sectionName: 'Pizza: Best price',
  },
  {
    products: [
      {
        id: '5',
        image: 'https://kingpizza.kh.ua/resources/products/20211123202045_366bb8053.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 255,
        toppings: 'mozzarela, peperoni, sause',
        name: 'Pizza Tony Peperoni',
      },
      {
        id: '6',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 255,
        toppings: '(double portion of mozzarella), mozzarella, Domino\'s sauce',
        name: 'Pizza Margherita',
      },
      {
        id: '7',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 260,
        toppings: 'chicken, onion, bacon, mushrooms, mozzarella, barbecue sauce',
        name: 'Pizza Barbecue',
      },
      {
        id: '8',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 255,
        toppings: 'corn, onion, mushrooms, bavarian sausages, mozzarella, barbecue sauce',
        name: 'Pizza Grill Mix',
      },
      {
        id: '9',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 271,
        toppings: 'onion, bacon, ham, mushrooms, mozzarella, Alfredo sauce',
        name: 'Pizza Carbonara',
      },
      {
        id: '10',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 275,
        toppings: 'onion, bacon, ham, mushrooms, mozzarella, pickled cucumbers, garlic sauce',
        name: 'Pizza Country',
      },
    ],
    sectionName: 'Pizza: Heroes',
  },
  {
    products: [
      {
        id: '11',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 294,
        toppings: 'feta, olives, mozzarella, garlic sauce, tuna',
        name: 'Pizza Greek',
      },
      {
        id: '12',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 290,
        toppings: 'chicken, feta, mozzarella, cherry tomatoes, Alfredo sauce, spinach',
        name: 'Pizza Tuscan',
      },
      {
        id: '13',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 295,
        toppings: 'jalapeno, bacon, mozzarella, pepperoni, tomatoes, Domino\'s sauce',
        name: 'Pizza Spicy',
      },
      {
        id: '14',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 286,
        toppings: 'bergader blue, bam, mozzarella, pepperoni, tomatoes, Alfredo sauce',
        name: 'Pizza Provence',
      },
      {
        id: '15',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 285,
        toppings: 'chicken, corn, jalapeno, pineapple, bell pepper, mushrooms, mozzarella, Domino\'s sauce',
        name: 'Pizza Jamaica Bombastic',
      },
      {
        id: '16',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 249,
        toppings: 'dip (burger sauce), chicken, onion, mushrooms, mozzarella, pickled cucumbers, Domino\'s sauce',
        name: 'Pizza Chicken kebab',
      },
    ],
    sectionName: 'Pizza: Weirdness',
  },
  {
    products: [
      {
        id: '17',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 294,
        toppings: 'ham, mustard, bavarian sausages, mozzarella, tomatoes, white sausages, barbecue sauce',
        name: 'Pizza Munich Deluxe',
      },
      {
        id: '18',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 286,
        toppings: 'meatballs, onion, bell pepper, mushrooms, mozzarella, parmesan, pepperoni, barbecue sauce',
        name: 'Pizza Deluxe Barbecue',
      },
      {
        id: '19',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 315,
        toppings: 'bacon, ham, bavarian sausages, mozzarella, parmesan, pepperoni, Domino\'s sauce',
        name: 'Pizza Mitz\'s',
      },
      {
        id: '20',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 310,
        toppings: 'meatballs, olives, onions, bell peppers, ham, mushrooms, mozzarella, pepperoni, Domino\'s sauce',
        name: 'Pizza Extravaganza',
      },
      {
        id: '21',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 310,
        toppings: 'double portion of steak meat (beef), dip (burger sauce), onion, mozzarella, barbecue sauce',
        name: 'Pizza Royal Cheeseburger',
      },
    ],
    sectionName: 'Pizza: Finest',
  },
  {
    products: [
      {
        id: '22',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 266,
        toppings: 'chicken, pineapple, mozzarella, Domino\'s sauce',
        name: 'Pizza Hawaiian',
      },
      {
        id: '23',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 272,
        toppings: 'chicken, bergader blue, mozzarella, alfredo sauce',
        name: 'Pizza Chicken-Dorblu',
      },
      {
        id: '24',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 310,
        toppings: 'feta, bergader blue, mozzarella, parmesan, alfredo sauce, cheddar',
        name: 'Pizza Five Cheese',
      },
      {
        id: '25',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 300,
        toppings: 'feta, olives, bell pepper, mushrooms, mozzarella, tomatoes, Alfredo sauce, spinach',
        name: 'Pizza Spinach and feta',
      },
      {
        id: '26',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/800px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
        sizes: Object.values(Size),
        doughSizes: [DoughSize.BOARD_HOT_DOG, DoughSize.PHILADELPHY, DoughSize.STANDART, DoughSize.THIN],
        cost: 320,
        toppings: 'philadelphia cream cheese, salmon, mozzarella, Alfredo sauce',
        name: 'Pizza Philadelphia Salmon',
      },
    ],
    sectionName: 'Pizza: Gourmet',
  },
];
